// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ToyStoreManagement.Infrastructure.Persistence;

#nullable disable

namespace ToyStoreManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523141138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("CART_ITEM_ID");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("CartItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("CART_ITEM", "C##ORACLEDB2026");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CATEGORY_NAME");

                    b.HasKey("CategoryId");

                    b.ToTable("CATEGORY", "C##ORACLEDB2026");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("FULL_NAME");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("PHONE");

                    b.HasKey("CustomerId");

                    b.ToTable("CUSTOMER", "C##ORACLEDB2026");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.InventoryReceipt", b =>
                {
                    b.Property<Guid>("InventoryReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("INVENTORY_RECEIPT_ID");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("RECEIVED_DATE");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("SUPPLIER_ID");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("NUMBER(18, 2)")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.HasKey("InventoryReceiptId");

                    b.HasIndex("SupplierId");

                    b.ToTable("INVENTORY_RECEIPTS", "C##ORACLEDB2026");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.InventoryReceiptDetail", b =>
                {
                    b.Property<Guid>("InventoryReceiptDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("INVENTORY_RECEIPT_DETAIL_ID");

                    b.Property<Guid>("InventoryReceiptId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("INVENTORY_RECEIPT_ID");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("NUMBER(18, 2)")
                        .HasColumnName("UNIT_PRICE");

                    b.HasKey("InventoryReceiptDetailId");

                    b.HasIndex("InventoryReceiptId");

                    b.HasIndex("ProductId");

                    b.ToTable("INVENTORY_RECEIPT_DETAILS", "C##ORACLEDB2026");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ORDER_ID");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("CUSTOMER_NAME");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CUSTOMER_PHONE");

                    b.Property<decimal>("Discount")
                        .HasColumnType("NUMBER(18, 2)")
                        .HasColumnName("DISCOUNT");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("NUMBER(18, 2)")
                        .HasColumnName("FINAL_AMOUNT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ORDER_DATE");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("SHIPPING_ADDRESS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("NUMBER(18, 2)")
                        .HasColumnName("TOTAL_AMOUNT");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ORDERS", "C##ORACLEDB2026");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ORDER_DETAIL_ID");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("ORDER_ID");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER(18, 2)")
                        .HasColumnName("PRICE");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ORDER_DETAILS", "C##ORACLEDB2026");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("MANUFACTURER");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MINIMUM_AGE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER(18, 2)")
                        .HasColumnName("PRICE");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("STOCK_QUANTITY");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PRODUCT", "C##ORACLEDB2026");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.HasKey("Id");

                    b.ToTable("SUPPLIERS", "C##ORACLEDB2026");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("ToyStoreManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.InventoryReceipt", b =>
                {
                    b.HasOne("ToyStoreManagement.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.InventoryReceiptDetail", b =>
                {
                    b.HasOne("ToyStoreManagement.Domain.Entities.InventoryReceipt", "InventoryReceipt")
                        .WithMany("Details")
                        .HasForeignKey("InventoryReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyStoreManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryReceipt");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.Order", b =>
                {
                    b.HasOne("ToyStoreManagement.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("ToyStoreManagement.Domain.Entities.Order", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyStoreManagement.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.Product", b =>
                {
                    b.HasOne("ToyStoreManagement.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.InventoryReceipt", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("ToyStoreManagement.Domain.Entities.Order", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
